[2024-08-05T12:44:49.215+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-05T12:44:49.257+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.first_task manual__2024-08-05T12:44:48.606855+00:00 [queued]>
[2024-08-05T12:44:49.265+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.first_task manual__2024-08-05T12:44:48.606855+00:00 [queued]>
[2024-08-05T12:44:49.265+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-08-05T12:44:49.279+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): first_task> on 2024-08-05 12:44:48.606855+00:00
[2024-08-05T12:44:49.287+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'first_task', 'manual__2024-08-05T12:44:48.606855+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp1j1_5pm2']
[2024-08-05T12:44:49.290+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=705) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-05T12:44:49.290+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask first_task
[2024-08-05T12:44:49.291+0000] {standard_task_runner.py:64} INFO - Started process 706 to run task
[2024-08-05T12:44:49.340+0000] {task_command.py:426} INFO - Running <TaskInstance: first_dag.first_task manual__2024-08-05T12:44:48.606855+00:00 [running]> on host 5bf363677985
[2024-08-05T12:44:49.437+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ayush' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-05T12:44:48.606855+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-05T12:44:48.606855+00:00'
[2024-08-05T12:44:49.439+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-05T12:44:49.478+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-05T12:44:49.479+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello wordl, this is the first task']
[2024-08-05T12:44:49.486+0000] {subprocess.py:86} INFO - Output:
[2024-08-05T12:44:49.488+0000] {subprocess.py:93} INFO - hello wordl, this is the first task
[2024-08-05T12:44:49.489+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-05T12:44:49.490+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-05T12:44:49.512+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=first_task, run_id=manual__2024-08-05T12:44:48.606855+00:00, execution_date=20240805T124448, start_date=20240805T124449, end_date=20240805T124449
[2024-08-05T12:44:49.546+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-05T12:44:49.559+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-05T12:44:49.561+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
